title: "eXPeDATE App"
email: marketing@expedate.app
timezone: UTC
url: https://expedate.app
baseurl: "/"
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/ktnew.svg"
author: eXPeDATE
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-016V8HJ3KD

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
